#!/bin/bash
if [ $# -ne 1 ] 
then
    echo "Error: missing argument."
    echo "Usage: $0 <username>"
    exit 1
fi

./buildout/bin/buildout -c buildout_$1.cfg

echo "Redemarrage tomcat"
sudo /etc/init.d/tomcat-tomcat1 restart

echo "Redemarrage apache"
sudo apache2ctl graceful

date