#!/bin/bash
if [ $# -ne 1 ] 
then
    echo "Error: missing argument."
    echo "Usage: $0 <username>"
    exit 1
fi

##echo ""
##echo "Arrêt tomcat"
##sudo /etc/init.d/tomcat-tomcat1 stop
##
##
make -f $1.mk build


echo ""
echo "Création modele pyramid_oereb pour ReservedAreas"
.build/venv/bin/create_standard_model -c ReservedAreas -g POLYGON -p .build/venv/lib/python2.7/site-packages/pyramid_oereb/standard/models -k TRUE

echo ""
echo "Suppressions des pdf sur instances rwunderlich et stage"
rm -rf /var/sig/sitj/_crdppf_prov/*.pdf

#echo ""
#echo "Redemarrage postgresql"
#sudo /etc/init.d/postgresql restart

echo ""
echo "Redemarrage tomcat"
sudo /etc/init.d/tomcat-tomcat1 restart

echo ""
echo "Redemarrage apache"
sudo apache2ctl graceful

date